language: c++
sudo: enabled
dist: trusty
compiler: g++

install:
  - wget https://root.cern.ch/download/root_v6.06.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
  - tar -xzf root_v6.06.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
  - . root/bin/thisroot.sh
  - HOME=`pwd`
  - touch ~/.bashrc
  - . ~/.bashrc
script:
  - cd .. && ./ChargedHiggs/install.sh && cd -

after_success:
  - mkdir -p ntuples/GluGlu_HToMuMu_M125_13TeV_powheg_pythia8
  - cd ntuples/GluGlu_HToMuMu_M125_13TeV_powheg_pythia8 && wget --no-check-certificate https://amarini.web.cern.ch/amarini/travis/NeroNtuples_1.root && cd -
  - python python/Loop.py -v -d dat/travis/input.dat
  - ls -ltr
