xsecsig = [
{"pro" : "ssWW", "cont": "EWK", "name": "WPMJJWPMJJjj_EWK_LO", "xsec" : 0.1258},
{"pro" : "ssWW", "cont": "QCD", "name": "WPMJJWPMJJjj_QCD_LO", "xsec" : 0.1083},
#{"pro" : "ssWW", "cont": "INT", "name": "WPMJJWPMJJjj_EWK_QCD_LO", "xsec" : 0.2448},
#
{"pro" : "osWW", "cont": "EWK", "name": "WPJJWMJJjj_EWK_LO", "xsec" : 1.8932},
{"pro" : "osWW", "cont": "QCD", "name": "WPJJWMJJjj_QCD_LO", "xsec" : 160.},
#{"pro" : "osWW", "cont": "INT", "name": "WPJJWMJJjj_EWK_QCD_LO", "xsec" : 161},
{"pro" : "osWW", "cont": "EWK", "name": "WPJJWMJJjj_4f_EWK_LO", "xsec" : 0.36680},
{"pro" : "osWW", "cont": "QCD", "name": "WPJJWMJJjj_4f_QCD_LO", "xsec" : 8.2610},
#
{"pro" : "WZ", "cont": "EWK", "name": "ZJJNOBWPMJJjj_EWK_LO", "xsec" : 0.4548},
{"pro" : "WZ", "cont": "QCD", "name": "ZJJNOBWPMJJjj_QCD_LO", "xsec" : 4.7207},
#{"pro" : "WZ", "cont": "INT", "name": "ZJJNOBWPMJJjj_EWK_QCD_LO", "xsec" : 5.1734},
{"pro" : "WZ", "cont": "EWK", "name": "ZBBWPMJJjj_EWK_LO", "xsec" : 0.1236},
{"pro" : "WZ", "cont": "QCD", "name": "ZBBWPMJJjj_QCD_LO", "xsec" : 1.264},
#{"pro" : "WZ", "cont": "INT", "name": "ZBBWPMJJjj_EWK_QCD_LO", "xsec" : 1.388},
{"pro" : "WZ", "cont": "EWK", "name": "ZBBWPMJJjj_4f_EWK_LO", "xsec" : 0.04626},
{"pro" : "WZ", "cont": "QCD", "name": "ZBBWPMJJjj_4f_QCD_LO", "xsec" : 1.178},
{"pro" : "WZ", "cont": "EWK", "name": "ZNUNUWPMJJjj_EWK_LO", "xsec" : 0.1652},
{"pro" : "WZ", "cont": "QCD", "name": "ZNUNUWPMJJjj_QCD_LO", "xsec" : 1.699},
#{"pro" : "WZ", "cont": "INT", "name": "ZNUNUWPMJJjj_EWK_QCD_LO", "xsec" : 1.865},
{"pro" : "WZ", "cont": "EWK", "name": "ZNUNUWPMJJjj_4f_EWK_LO", "xsec" : 0.06303},
{"pro" : "WZ", "cont": "QCD", "name": "ZNUNUWPMJJjj_4f_QCD_LO", "xsec" : 1.5950},
{"pro" : "WZ", "cont": "EWK", "name": "ZJJWPMJJjj_4f_EWK_LO", "xsec" : 0.1674},
{"pro" : "WZ", "cont": "QCD", "name": "ZJJWPMJJjj_4f_QCD_LO", "xsec" : 4.255},
##
{"pro" : "ZZ", "cont": "EWK", "name": "ZJJZJJjj_EWK_LO", "xsec" : 0.0533},
{"pro" : "ZZ", "cont": "QCD", "name": "ZJJZJJjj_QCD_LO", "xsec" : 1.084},
#{"pro" : "ZZ", "cont": "INT", "name": "ZJJZJJjj_EWK_QCD_LO", "xsec" : 1.143},
{"pro" : "ZZ", "cont": "EWK", "name": "ZNUNUZJJjj_EWK_LO", "xsec" : 0.0312},
{"pro" : "ZZ", "cont": "QCD", "name": "ZNUNUZJJjj_QCD_LO", "xsec" : 0.6352},
#{"pro" : "ZZ", "cont": "INT", "name": "ZNUNUZJJjj_EWK_QCD_LO", "xsec" : 0.6698},
####semi-lep
{"pro" : "ssWW", "cont": "EWK", "name": "WMLEPWMHADjj_EWK_LO", "xsec" : 0.0323},
{"pro" : "ssWW", "cont": "EWK", "name": "WPLEPWPHADjj_EWK_LO", "xsec" : 0.0873},
{"pro" : "ssWW", "cont": "QCD", "name": "WMLEPWMHADjj_QCD_LO", "xsec" : 0.0318},
{"pro" : "ssWW", "cont": "QCD", "name": "WPLEPWPHADjj_QCD_LO", "xsec" : 0.0727},
#
{"pro" : "osWW", "cont": "EWK", "name": "WPHADWMLEPjj_EWK_LO", "xsec" : 0.9464},
{"pro" : "osWW", "cont": "EWK", "name": "WPLEPWMHADjj_EWK_LO", "xsec" : 0.9464},
{"pro" : "osWW", "cont": "EWK", "name": "WPHADWMLEPjj_4f_EWK_LO", "xsec" : 0.184},
{"pro" : "osWW", "cont": "EWK", "name": "WPLEPWMHADjj_4f_EWK_LO", "xsec" : 0.183},
{"pro" : "osWW", "cont": "QCD", "name": "WPHADWMLEPjj_QCD_LO", "xsec" : 76.19},
{"pro" : "osWW", "cont": "QCD", "name": "WPLEPWMHADjj_QCD_LO", "xsec" : 76.19},
{"pro" : "osWW", "cont": "QCD", "name": "WPHADWMLEPjj_4f_QCD_LO", "xsec" : 4.126},
{"pro" : "osWW", "cont": "QCD", "name": "WPLEPWMHADjj_4f_QCD_LO", "xsec" : 4.126},
#
{"pro" : "WZ", "cont": "EWK", "name": "WPLEPZHADjj_EWK_LO", "xsec" : 0.1814},
{"pro" : "WZ", "cont": "EWK", "name": "WMLEPZHADjj_EWK_LO", "xsec" : 0.0996},
{"pro" : "WZ", "cont": "QCD", "name": "WPLEPZHADjj_QCD_LO", "xsec" : 1.782},
{"pro" : "WZ", "cont": "QCD", "name": "WMLEPZHADjj_QCD_LO", "xsec" : 1.086},
]
